### ISSUE TITLE
IEEE update

### ISSUE THREAD

**Issue by gurues** [xyzroe/ZigStarGW-MT#13]
Hello
I did not update the IEEE. I change the current IEEE of the sonoff dongle P for the old one of my zigbee2mqtt network but it does not update it finishing without errors "All is OK. Restarting Zigbee

Thank you

**Comment by xyzroe** [comment]
I need more information, screenshots, a more detailed description of what you have done. You didn't provide enough.

**Comment by gurues** [comment]
Hello, thanks for your interest. I attach a link with photos and video
[https://drive.google.com/drive/folders/16NLz8deIrXXoNof4YD9eJ4qIpnNH_FvH?usp=sharing](url)

**Comment by xyzroe** [comment]
You must write ieee in one time with flashing.
It doesn't work if apply without flashing. 

About your video - I think you upload wrong video.

**Comment by xyzroe** [comment]
Could you check https://github.com/JelmerT/cc2538-bsl/issues/127 ?
I thinks it is yours situation.

**Comment by brugk000** [comment]
Hello,
I have the samen problem as @gurues with the zigstar lan gateway. IEEE is not updated during reflashing.

**Comment by xyzroe** [comment]
@gurues @brugk000 This problem is not Multitool problem, but architecture of 2652. We can read only one address - primary one, but when we write it uses secondary one. zigbee2mqtt currently uses only primary one.

This is nicely covered in the JelmerT's issue I linked to earlier.
