### ISSUE TITLE
cannot write IEEE address on Zigstar Stick V4

### ISSUE THREAD

**Issue by luci84tm** [xyzroe/ZigStarGW-MT#15]
I cannot write my old stick address on a Zigstar stick V4. 
The stick gets into BSL and the write shows as successful, but it resets it's value to the original IEEE. 
Even after erase, firmware write.. I tried all possibilities.

Any idea why I cannot write the IEEE address ?

P.S. I used the latest version v0.3.5

**Comment by xyzroe** [comment]
Repeated issue https://github.com/xyzroe/ZigStarGW-MT/issues/13
