### ISSUE TITLE
IEEE write not working with Sonoff dongle

### ISSUE THREAD

**Issue by angcop** [xyzroe/ZigStarGW-MT#16]
With Sonoff Dongle Plus (ZbDongle-P), when I introduce the IEE from the other coordinator:
- IEEE field filled with the address of another coordinador
- Right side, with only "Write IEEE" and with nothing markes, in both cases after pressing "Write IEEE" no error reported, but the original IEEE it's refreshed in the field, not the one introduced.

**Comment by xyzroe** [comment]
Repeated
https://github.com/xyzroe/ZigStarGW-MT/issues/13
