### ISSUE TITLE
can't read Zigbee configuration 

### ISSUE THREAD

**Issue by diemon24** [xyzroe/ZigStarGW-MT#18]
when I restore configuration Zigbee module, in macOS version can't read Zigbee configuration. zigpy_znp.tools Unknown error. I open json file with configuration, zigstar program starting and ending with error 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/91910101/219678729-2bceeda9-632b-42d7-84f3-821104956bbf.png">

**Comment by xyzroe** [comment]
Duplicate #14
