### ISSUE TITLE
[REQUEST] Silicon Labs EFR32 Flasher support in the ZigStar Multi Tool application?

### ISSUE THREAD

**Issue by Hedda** [xyzroe/ZigStarGW-MT#21]
@xyzroe any chance you consider adding Silicon Labs EFR32 Flasher support in the ZigStar Multi Tool application?

Could code from @mercenaruss ZigStar Silabs-Flasher (fork of [Nabu Casa's universal-silabs-flasher](https://github.com/NabuCasa/universal-silabs-flasher)) maybe be used base for that?

https://github.com/mercenaruss/zigstar_addons/tree/main/zigstar-silabs-flasher

By the way, recommend check out darkxst's fork which fixes some issues and adds better support for other adapters:

https://github.com/darkxst/multipan_flasher

**Comment by xyzroe** [comment]
No.

**Comment by xyzroe** [comment]
Unfortunately, I don’t have free time for this project at the moment. Besides, I don’t use chips from Silabs, so it seems to me that I’m unlikely to do this, even if I have time.

@Hedda I see that you are quite well versed in Zigbee, you know various projects and their forks, you have the enthusiasm to open an issues all over Github, maybe you should try programming? Python is not a very difficult language.
But you will be able to make a HUGE contribution to the community. You should try, I think so.

**Comment by Hedda** [comment]
> maybe you should try programming? Python is not a very difficult language.

While the enthusiasm is there and I have tried to learn "real" programming, I do not have the free time either and not just for the moment as kids, wife, house, full-time job, training and other hobbies, as well as having ADHD, OCD and dyslexia, gets in the way.
