### ISSUE TITLE
error: local variable 'chip' referenced before assignment

### ISSUE THREAD

**Issue by Stadicus** [xyzroe/ZigStarGW-MT#22]
I'm trying to flash the ZigStar UZG device (version 0.3) with the CC1352P7 chip according to their instructions: https://uzg.zig-star.com/flashing-and-updating/#multi-tool-ethernet

Flashing [CC1352P7_coordinator_20230507.hex](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) I get the following command line output on Ubuntu:

```bash
$ python ZigStarGW-MT.py
Opening port socket://192.168.1.5:6638, baud 500000
Reading data from /home/stadicus/github/ZigStarGW-MT/CC1352P7_coordinator_20230507.hex
Firmware file: Intel Hex
Connecting to target...
local variable 'chip' referenced before assignment
```

The progress bar immediately shows 100%, with the same error message in the status row below.

Any thoughts how to get the flashing process working?

**Comment by mercenaruss** [comment]
@Stadicus unfortunately the tool dont support currently CC262P7,use the addon https://github.com/mercenaruss/zigstar_addons

**Comment by Stadicus** [comment]
Thanks! I've tried the ZigStar Addon and had some issues, but that's not for this issue. I'll give it another shot.

**Comment by olylak** [comment]
I'm getting the same error when trying to flash ZigStar UZG-01 device with MT of version 0.3.8.

![image](https://github.com/xyzroe/ZigStarGW-MT/assets/3715218/36d3381a-82ff-46cf-ad31-f6cb423047e4)

![image](https://github.com/xyzroe/ZigStarGW-MT/assets/3715218/4e2cbbc8-ca1b-4232-a022-72fe64fa9909)

Could you please advise what is the problem here?

Thanks.

**Comment by xyzroe** [comment]
Could you try this one https://github.com/xyzroe/ZigStarGW-MT/releases/tag/v0.4.0 ?

**Comment by xyzroe** [comment]
v0.4.1 should fix this error
