### ISSUE TITLE
UZG-01 CC2652P flashing error: local variable 'chip' referenced before assignment

### ISSUE THREAD

**Issue by olylak** [xyzroe/ZigStarGW-MT#23]
Hello,

I'm follwing instruction https://uzg.zig-star.com/flashing-and-updating/#multi-tool-ethernet to flash UZG-01 based on the CC2652P  chip with the following firmware: https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20230507.zip

And getting similar issue as decribed here https://github.com/xyzroe/ZigStarGW-MT/issues/22 with the only difference that it is CC2652P chip.

`local variable 'chip' referenced before assignment`

![image](https://github.com/xyzroe/ZigStarGW-MT/assets/3715218/827c88e8-9222-4045-b1df-38d9b15ddade)
![image](https://github.com/xyzroe/ZigStarGW-MT/assets/3715218/3dc91267-a6f1-4a75-a51f-e814c8570b7b)

Could you please advise what is the problem here?

Thanks.

**Comment by xyzroe** [comment]
Could you try this one https://github.com/xyzroe/ZigStarGW-MT/releases/tag/v0.4.0 ?

**Comment by xyzroe** [comment]
But check twice which chip do you have BEFORE flashing. Don't look at ZigStar web UI CC2652 version and flash size - these field are just constant text. There is not any chip identifying function in current version of firmware.

**Comment by olylak** [comment]
This is a duplicate topic. Please look here: https://github.com/mercenaruss/uzg-firmware/issues/8

**Comment by xyzroe** [comment]
You should try 0.4.1
