### ISSUE TITLE
Firmware flashing extremely slow

### ISSUE THREAD

**Issue by okastl** [xyzroe/ZigStarGW-MT#24]
At least on my Windows 10 machine firmware flashing is extremely slow.
This is caused by Nagle algorithm, because of writing some bytes, waiting for ack, ....
As you have cc2538-bsl.py local anyway, you can add these lines to make flash upload really fast.
I tested it by running cc2538-bsl.py from command line:

```
import socket

...

# in function def open()
        self.sp.open()
        if hasattr(self.sp, '_socket'):
            self.sp._socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

```

Thank you!

**Comment by xyzroe** [comment]
@okastl many thanks! 

look at [v0.4.2](https://github.com/xyzroe/ZigStarGW-MT/releases/tag/v0.4.2)
