### ISSUE TITLE
Out of date documentation regarding MultiTool

### ISSUE THREAD

**Issue by s-b-n** [xyzroe/ZigStarGW-MT#26]
### Problem
I tried to flash my UZG-01 with the newest firmware via ZigStar MultiTool following the [documentation ](https://uzg.zig-star.com/flashing-and-updating/#multi-tool-ethernet) and couldn't finish the flash because I was using a version < 0.4.

I dowloaded the MultiTool following the link in the documentation: https://github.com/xyzroe/ZigStarGW-MT/releases/tag/v0.3.5

### Solution
Update the link to the latest version or use the latest tag: https://github.com/xyzroe/ZigStarGW-MT/releases/latest.

**Comment by xyzroe** [comment]
I'm not the owner of a zig-star.com

**Comment by mercenaruss** [comment]
This will be updated,please close the issue.

**Comment by s-b-n** [comment]
> I'm not the owner of a zig-star.com

Sorry, I wasn't aware of that! But I guess @mercenaruss got the info anyway! :) Will close the issue now!

**Comment by s-b-n** [comment]
> I'm not the owner of a zig-star.com

Sorry, I wasn't aware of that! But I guess @mercenaruss got the info anyway! :) Will close the issue now!
