### ISSUE TITLE
Changing ieee

### ISSUE THREAD

**Issue by Toolhead** [xyzroe/ZigStarGW-MT#27]
I want to change the ieee on my Sonoff Dongle P.
Choose firmware file, tick the boxes on the right side, including "write ieee".
I copy the wanted address in the box.
But when I hit "start" it changes the address back to the original one of the adapter.

**Comment by xyzroe** [comment]
Because writing is going on the second IEEE, while reading goes on main IEEE.
TI doesn't support rewriting main IEEE.
