### ISSUE TITLE
Consider switching to Electrorama's llama-bsl fork of cc2538-bsl

### ISSUE THREAD

**Issue by Hedda** [xyzroe/ZigStarGW-MT#3]
@xyzroe @mercenaruss FYI, cc2538-bsl is quite stable but probably seen JelmerT is not so much longer actively developing it.

Might want to consider switching to Electrorama's llama-bsl fork of cc2538-bsl if @omerk will continue development on it:

https://github.com/electrolama/llama-bsl

Guess he does not have a lot of time either however he have great ideas on making it more user-friendly and easy to use:

https://github.com/electrolama/llama-bsl/issues

Personally, I especially like the idea he posted to Koenkk about adding index.json with a list of firmware updates to his Z-Stack-firmware repo so that it can be used by other software an index for or automatic firmware downloads for board types/roles:

https://github.com/Koenkk/Z-Stack-firmware/issues/310

**Comment by xyzroe** [comment]
At the moment, I do not see the difference between them in the context we need.

I see a lot of ideas. But there is no implementation yet.

The ability to download firmware automatically is cool, but I need to implement it differently.

Perhaps when that will be the time.

**Comment by Hedda** [comment]
@xyzroe one new feature that I believe has already been implemented is automatic download of firmware for known adapters:

https://github.com/Koenkk/Z-Stack-firmware/issues/310

https://github.com/Koenkk/Z-Stack-firmware/pull/311

https://github.com/electrolama/llama-bsl/issues/12

This feature uses a new index.json that Koenkk now has in his Z-Stack-firmware repository on GitHub which can be used for it:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/index.json
