### ISSUE TITLE
Can't read nvram from Sonoff USB stick

### ISSUE THREAD

**Issue by Napalmcold** [xyzroe/ZigStarGW-MT#7]
Hi!

Tried to read nvram before updating the firmware of the Sonoff ZigBee stick, but getting this all the time:
![image](https://user-images.githubusercontent.com/32687587/151989930-fab95c69-f8e9-41e6-be15-6b921b897b1e.png)
Tried different laptops also.

**Comment by xyzroe** [comment]
I'm pretty sure the wrong com port is selected.
You may not have installed the driver for usb-uart that is used in sonoff.
