### ISSUE TITLE
ZigStarGW-MT-x64.exe.zip doesn't work

### ISSUE THREAD

**Issue by pinggi** [xyzroe/ZigStarGW-MT#8]
1. I ran ZigStarGW-MT.exe and nothing happened.
2. I noticed  the process took 100% of one core - in background - it didn't show GUI.
3. I had to kill it.

Tested on Win 10 x64.

**Comment by xyzroe** [comment]
Because this is a self-extracting Python software, you just need to wait a little longer.
works for everyone (more than 10k downloads)
