### ISSUE TITLE
Error while trying to enable BSL mode, Zigstar LAN

### ISSUE THREAD

**Issue by flaektrem** [xyzroe/ZigStarGW-MT#9]
Tried to update FW in my Zigstar LAN Gateway but it just gives me this error.
Anyone have an idea?

![Skärmbild 2022-04-14 223144](https://user-images.githubusercontent.com/58172129/163471182-55ee798b-3f54-4a86-91f2-bd1b58a49a81.png)

**Comment by xyzroe** [comment]
What type of ESP32 FW do you use?

**Comment by flaektrem** [comment]
Maybe 0.6.2, right?

![Screenshot_20220415-073946](https://user-images.githubusercontent.com/58172129/163526299-60cc9cea-5a3c-4a4b-b7d6-fbe9a056c583.jpg)

**Comment by flaektrem** [comment]
Just updated to 0.6.4. Same error message still shows up.

**Comment by xyzroe** [comment]
It's really not clear, for me and for many others it works without problems in automatic mode.

maybe there is more information?

**Comment by flaektrem** [comment]
> It's really not clear, for me and for many others it works without problems in automatic mode.
> 
> maybe there is more information?

What more information do you need? 
I was not able to enable BSL automatically and I don't know why

**Comment by xyzroe** [comment]
for example, did you enter the address yourself, or did the program find it automatically?
did you edit the address field?
did you manage to repeat this problem again?
maybe on a different version?

**Comment by flaektrem** [comment]
The program found correct IP automatically. Did not edit anything. 
After i updated everything manually i haven't tested the auto mode again. 
Maybe a new version out now so I can test auto mode again and see if the problem persists

**Comment by mihsu81** [comment]
I'm facing the same issue and it is caused by the web server authentication. Auto BSL works only when authentication is not enabled.

**Comment by xyzroe** [comment]
@mihsu81 thanks for idea. Indeed, when authentication is enabled, Auto BSL does not work, this is normal behavior.
@flaektrem maybe you also use authentication?
